version: "3.9"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11.6}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/vespadb/
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: app
    tty: true
    ports:
      - "8001:8000"
    volumes:
      - .:/workspaces/vespadb/
    command: [ "serve", "--dev" ]
    working_dir: /workspaces/vespadb/
    environment:
      - PYTHONPATH=/workspaces/vespadb
      - DEBUG=True
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: vespadb
      POSTGRES_USER: vespauser
      POSTGRES_PASSWORD: vespauserpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery-worker
    volumes:
      - .:/workspaces/vespadb/
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery-beat
    volumes:
      - .:/workspaces/vespadb/
    depends_on:
      - db
      - redis

volumes:
  postgres_data:


networks:
  default:
    name: vespadb-network
