version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend-prod
    ports:
      - "3000:80"
    volumes:
      - ./src/frontend:/app