# Generated by Django 5.0.3 on 2024-04-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_province'),
        ('users', '0002_vespauser_personal_data_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='vespauser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vespauser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='observations.province'),
        ),
    ]
