# Generated by Django 5.0.4 on 2024-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_vespauser_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vespauser',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
    ]
