# Generated by Django 5.0.6 on 2024-07-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vespauser_reservation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vespauser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('sync', 'SYNC'), ('import', 'IMPORT')], default='regular', max_length=10),
        ),
    ]
