# Generated by Django 5.1.2 on 2024-11-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_vespauser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vespauser',
            name='personal_data_access',
        ),
    ]
