# Generated by Django 5.1.4 on 2025-03-22 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_vespauser_personal_data_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfServiceAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms of Service Acceptance',
                'verbose_name_plural': 'Terms of Service Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
