# Generated by Django 5.1.4 on 2025-03-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_termsofserviceacceptance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsOfServiceAcceptance',
        ),
    ]
