# Generated by Django 5.0.2 on 2024-02-23 15:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('OA', 'Observations API'), ('UR', 'User'), ('IM', 'Import')], default='OA', max_length=2)),
                ('status', models.CharField(choices=[('UT', 'Untreated'), ('TR', 'Treated')], default='UT', max_length=2)),
                ('validated', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('deleted', models.BooleanField(default=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
                ('reporter_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reported_datetime', models.DateTimeField()),
                ('extermination_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.JSONField(default=list)),
                ('nature_reserve', models.BooleanField()),
                ('nest_height', models.CharField(blank=True, choices=[('BL4', 'Below 4 meters'), ('AB4', 'Above 4 meters')], max_length=3, null=True)),
                ('nest_location', models.CharField(blank=True, choices=[('OUB', 'Outdoor, uncovered on building'), ('OUT', 'Outdoor, uncovered in tree or bush'), ('OCS', 'Outdoor, covered by structure'), ('ONC', 'Outdoor, naturally covered'), ('IIB', 'Indoor, in building or structure'), ('UNK', 'Unknown')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, max_length=5000, null=True)),
                ('nest_type', models.CharField(blank=True, choices=[('AEM', 'Active embryonic nest'), ('APR', 'Active primary nest'), ('ASE', 'Active secondary nest'), ('IEM', 'Inactive/empty nest'), ('POT', 'Potential nest (more info needed)'), ('OSP', 'Nest of another species'), ('NON', 'No nest (object, insect)')], max_length=3, null=True)),
                ('feedback_provided', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('managed', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('duplicate', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('public_domain', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('result', models.CharField(choices=[('SUC', 'Successfully treated'), ('NST', 'Not successfully treated'), ('NTR', 'Not treated'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('problems', models.CharField(choices=[('NON', 'None'), ('STI', 'Stings'), ('NFAL', 'Nest fallen'), ('DIZ', 'Dizziness/nausea'), ('CHE', 'Chemical projection'), ('UNK', 'Unknown')], default='UNK', max_length=4)),
                ('care', models.CharField(choices=[('NFR', 'Nest fully removed'), ('NPR', 'Nest partially removed'), ('NLH', 'Nest left hanging'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('product', models.CharField(choices=[('PER', 'Permas-D'), ('LN', 'Liquid nitrogen'), ('VF', 'Vespa Ficam D'), ('TP', 'Topscore PAL'), ('EAE', 'Ether/aceton/ethyl acetate'), ('DE', 'Diatomaceous earth'), ('OTH', 'Other'), ('NON', 'None'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('method', models.CharField(choices=[('FRZ', 'Freezing'), ('TLP', 'Telescopic pole'), ('SC', 'Sealable container/box'), ('LS', 'Liquid sprayer'), ('PS', 'Powder sprayer'), ('NT', 'Not treated'), ('OTH', 'Other'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('extermination_file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('extermination_photos', models.JSONField(default=list)),
                ('ANB_area', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('province', models.CharField(choices=[('WF', 'West Flanders'), ('EF', 'East Flanders'), ('ANT', 'Antwerp'), ('FB', 'Flemish Brabant'), ('LIM', 'Limburg'), ('NF', 'Non-Flemish'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('exterminator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nests_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nest',
                'verbose_name_plural': 'Nests',
            },
        ),
    ]
