# Generated by Django 5.0.2 on 2024-02-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='external_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
