# Generated by Django 5.0.3 on 2024-03-19 12:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wn_id', models.IntegerField(unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source', models.CharField(max_length=255)),
                ('wn_notes', models.TextField(blank=True, null=True)),
                ('wn_admin_notes', models.TextField(blank=True, null=True)),
                ('species', models.IntegerField()),
                ('nest_height', models.CharField(choices=[('lager_dan_4_meter', 'Lager dan 4 meter'), ('hoger_dan_4_meter', 'Hoger dan 4 meter')], max_length=50)),
                ('nest_size', models.CharField(choices=[('minder_dan_25_cm', 'Minder dan 25 cm'), ('meer_dan_25_cm', 'Meer dan 25 cm')], max_length=50)),
                ('nest_location', models.CharField(choices=[('buiten_onbedekt_op_gebouw', 'Buiten, onbedekt op gebouw'), ('buiten_onbedekt_in_boom_of_struik', 'Buiten, onbedekt in boom of struik'), ('buiten_maar_overdekt_door_constructie', 'Buiten, maar overdekt door constructie'), ('buiten_natuurlijk_overdekt', 'Buiten, natuurlijk overdekt'), ('binnen_in_gebouw_of_constructie', 'Binnen, in gebouw of constructie'), ('onbekend', 'Onbekend')], max_length=50)),
                ('nest_type', models.CharField(choices=[('AH_actief_embryonaal_nest', 'AH - actief embryonaal nest'), ('AH_actief_primair_nest', 'AH - actief primair nest'), ('AH_actief_secundair_nest', 'AH - actief secundair nest'), ('AH_inactief_leeg_nest', 'AH - inactief/leeg nest'), ('AH_potentieel_nest', 'AH - potentieel nest (meer info nodig)'), ('nest_andere_soort', 'Nest andere soort'), ('geen_nest', 'Geen nest (object, insect)')], max_length=50)),
                ('observer_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('observer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observer_allows_contact', models.BooleanField(default=False)),
                ('observation_datetime', models.DateTimeField()),
                ('wn_cluster_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('eradication_datetime', models.DateTimeField(blank=True, null=True)),
                ('eradicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eradication_result', models.CharField(choices=[('successful', 'Succesvol behandeld'), ('unsuccessful', 'Niet succesvol behandeld'), ('untreated', 'Niet behandeld'), ('unknown', 'Onbekend')], max_length=50)),
                ('eradication_product', models.CharField(blank=True, choices=[('Permas-D', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('Vespa_Ficam_D', 'Vespa Ficam D'), ('Topscore_PAL', 'Topscore PAL'), ('ether_aceton_ethyl_acetate', 'Ether/aceton/ethyl acetate'), ('diatomeeenaarde', 'Diatomeënaarde'), ('andere', 'Andere'), ('geen', 'Geen'), ('onbekend', 'Onbekend')], max_length=50, null=True)),
                ('eradication_notes', models.TextField(blank=True, null=True)),
                ('wn_modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('wn_created_datetime', models.DateTimeField(blank=True, null=True)),
                ('duplicate', models.BooleanField(default=False)),
                ('images', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_observations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
