# Generated by Django 5.0.3 on 2024-03-06 14:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("species", models.IntegerField()),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_modification_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=255)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_modification_datetime", models.DateTimeField(auto_now=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("source", models.CharField(max_length=255)),
                ("validation_status", models.CharField(max_length=1)),
                ("validated", models.BooleanField(blank=True, default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("species", models.IntegerField()),
                ("activity", models.CharField(max_length=255)),
                ("attributes", models.JSONField(default=list)),
                ("images", models.JSONField(default=list)),
                (
                    "reporter_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("reporter_email", models.EmailField(max_length=254)),
                ("reported_datetime", models.DateTimeField()),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="observations.cluster",
                    ),
                ),
            ],
        ),
    ]
