# Generated by Django 5.0.3 on 2024-03-21 20:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_municipality_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='datpublbs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='lengte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='numac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='oidn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='oppervl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='terrid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='uidn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=31370),
        ),
    ]
