# Generated by Django 5.0.3 on 2024-03-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_municipality_datpublbs_municipality_lengte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='lengte',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='oppervl',
            new_name='surface',
        ),
    ]
