# Generated by Django 5.0.3 on 2024-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_anb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anb',
            name='administrator',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
