# Generated by Django 5.0.3 on 2024-03-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_municipality_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='observations.municipality'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
