# Generated by Django 5.0.3 on 2024-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_anb_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anb',
            name='contact',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anb',
            name='liberties',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anb',
            name='regio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
