# Generated by Django 5.0.3 on 2024-03-27 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_rename_lengte_municipality_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='anb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='reserved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
