# Generated by Django 5.0.3 on 2024-04-03 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_anb_contact_alter_anb_liberties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nis_code', models.CharField(max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=31370)),
                ('oidn', models.BigIntegerField(blank=True, null=True)),
                ('uidn', models.BigIntegerField(blank=True, null=True)),
                ('terrid', models.BigIntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
