# Generated by Django 5.0.4 on 2024-04-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='observations.province'),
        ),
    ]
