# Generated by Django 5.0.4 on 2024-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_municipality_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(blank=True, choices=[('Permas-D', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('Vespa_Ficam_D', 'Vespa Ficam D'), ('Topscore_PAL', 'Topscore PAL'), ('ether_aceton_ethyl_acetate', 'Ether/aceton/ethyl acetate'), ('diatomeeënaarde', 'Diatomeeënaarde'), ('andere', 'Andere'), ('geen', 'Geen'), ('onbekend', 'Onbekend')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_location',
            field=models.CharField(choices=[('buiten_onbedekt_op_gebouw', 'Buiten, onbedekt op gebouw'), ('buiten_onbedekt_in_boom_of_struik', 'Buiten, onbedekt in boom of struik'), ('buiten_maar_overdekt_door_constructie', 'Buiten, maar overdekt door constructie'), ('buiten_natuurlijk_overdekt', 'Buiten, natuurlijk overdekt'), ('binnen_in_gebouw_of_constructie', 'Binnen, in gebouw of constructie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_size',
            field=models.CharField(choices=[('kleiner_dan_25_cm', 'Kleiner dan 25 cm'), ('groter_dan_25_cm', 'Groter dan 25 cm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_type',
            field=models.CharField(choices=[('actief_embryonaal_nest', 'actief embryonaal nest'), ('actief_primair_nest', 'actief primair nest'), ('actief_secundair_nest', 'actief secundair nest'), ('inactief_leeg_nest', 'inactief/leeg nest'), ('potentieel_nest', 'potentieel nest')], max_length=50),
        ),
    ]
