# Generated by Django 5.0.4 on 2024-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_alter_observation_eradication_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='eradication_aftercare',
            field=models.CharField(blank=True, choices=[('nest_volledig_verwijderd', 'Nest volledig verwijderd'), ('nest_gedeeltelijk_verwijderd', 'Nest gedeeltelijk verwijderd'), ('nest_laten_hangen', 'Nest laten hangen')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='eradication_duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='eradication_method',
            field=models.CharField(blank=True, choices=[('diepvries', 'Diepvries'), ('telescoopsteel', 'Telescoopsteel'), ('afsluitbaar potje/doos', 'Afsluitbaar potje/doos'), ('vloeistofverstuiver', 'Vloeistofverstuiver'), ('poederverstuiver', 'Poederverstuiver')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='eradication_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='eradication_problems',
            field=models.CharField(blank=True, choices=[('stinging', 'Steken'), ('nest_falling', 'Nest gevallen'), ('dizziness', 'Duizeligheid'), ('poison_projection', 'Gif projectie')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='public_domain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='wn_validation_status',
            field=models.CharField(blank=True, choices=[('successful', 'Succesvol behandeld')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(choices=[('Permas-D', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('Vespa_Ficam_D', 'Vespa Ficam D'), ('Topscore_PAL', 'Topscore PAL'), ('ether_aceton_ethyl_acetate', 'Ether/aceton/ethyl acetate'), ('diatomeeënaarde', 'Diatomeeënaarde'), ('andere', 'Andere')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_height',
            field=models.CharField(blank=True, choices=[('lager_dan_4_meter', 'Lager dan 4 meter'), ('hoger_dan_4_meter', 'Hoger dan 4 meter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_location',
            field=models.CharField(blank=True, choices=[('buiten_onbedekt_op_gebouw', 'Buiten, onbedekt op gebouw'), ('buiten_onbedekt_in_boom_of_struik', 'Buiten, onbedekt in boom of struik'), ('buiten_maar_overdekt_door_constructie', 'Buiten, maar overdekt door constructie'), ('buiten_natuurlijk_overdekt', 'Buiten, natuurlijk overdekt'), ('binnen_in_gebouw_of_constructie', 'Binnen, in gebouw of constructie')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_size',
            field=models.CharField(blank=True, choices=[('kleiner_dan_25_cm', 'Kleiner dan 25 cm'), ('groter_dan_25_cm', 'Groter dan 25 cm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_type',
            field=models.CharField(blank=True, choices=[('actief_embryonaal_nest', 'actief embryonaal nest'), ('actief_primair_nest', 'actief primair nest'), ('actief_secundair_nest', 'actief secundair nest'), ('inactief_leeg_nest', 'inactief/leeg nest'), ('potentieel_nest', 'potentieel nest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
