# Generated by Django 5.0.4 on 2024-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_observation_eradication_aftercare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(blank=True, choices=[('Permas-D', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('Vespa_Ficam_D', 'Vespa Ficam D'), ('Topscore_PAL', 'Topscore PAL'), ('ether_aceton_ethyl_acetate', 'Ether/aceton/ethyl acetate'), ('diatomeeënaarde', 'Diatomeeënaarde'), ('andere', 'Andere')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_result',
            field=models.CharField(blank=True, choices=[('successful', 'Succesvol behandeld'), ('unsuccessful', 'Niet succesvol behandeld'), ('untreated', 'Niet behandeld'), ('unknown', 'Onbekend')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='wn_validation_status',
            field=models.CharField(blank=True, choices=[('onbekend', 'Unknown'), ('goedgekeurd_met_bewijs', 'Approved (with evidence)'), ('goedgekeurd_door_admin', 'Approved (by admin)'), ('goedgekeurd_automatische_validatie', 'Approved (automatic validation)'), ('in_behandeling', 'In progress'), ('afgewezen', 'Rejected'), ('nog_niet_te_beoordelen', 'Not evaluable yet')], max_length=50, null=True),
        ),
    ]
