# Generated by Django 5.0.4 on 2024-05-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_alter_observation_eradication_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='observer_allows_contact',
        ),
    ]
