# Generated by Django 5.0.4 on 2024-05-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_remove_observation_observer_allows_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='duplicate',
            new_name='visible',
        ),
    ]
