# Generated by Django 5.0.4 on 2024-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_rename_duplicate_observation_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
