# Generated by Django 5.0.4 on 2024-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_alter_observation_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='wn_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
