# Generated by Django 5.0.4 on 2024-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_alter_observation_wn_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_received_email',
            field=models.BooleanField(default=False),
        ),
    ]
