# Generated by Django 5.0.4 on 2024-05-22 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_rename_notes_observation_admin_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='observation',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('name',)},
        ),
    ]
