# Generated by Django 5.0.6 on 2024-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_alter_municipality_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
