# Generated by Django 5.0.6 on 2024-06-26 21:46

from django.db import migrations, models

def convert_time_to_string(apps, schema_editor):
    Observation = apps.get_model('observations', 'Observation')
    for observation in Observation.objects.all():
        if observation.eradication_duration:
            observation.eradication_duration = str(observation.eradication_duration)
            observation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_alter_municipality_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_time_to_string),
        migrations.AlterField(
            model_name='observation',
            name='eradication_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]