# Generated by Django 5.0.6 on 2024-06-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_alter_observation_eradication_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='eradication_datetime',
            new_name='eradication_date',
        ),
    ]
