# Generated by Django 5.0.6 on 2024-06-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_rename_eradication_datetime_observation_eradication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_method',
            field=models.CharField(blank=True, choices=[('diepvries', 'Diepvries'), ('telescoopsteel', 'Telescoopsteel'), ('doos', 'doos'), ('vloeistofverstuiver', 'Vloeistofverstuiver'), ('poederverstuiver', 'Poederverstuiver')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_problems',
            field=models.CharField(blank=True, choices=[('steken', 'Steken'), ('nest_gevallen', 'Nest gevallen'), ('duizeligheid', 'Duizeligheid'), ('gif_spuiten', 'Gif Spuiten')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(blank=True, choices=[('permas_d', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('vespa_ficam_d', 'Vespa Ficam D'), ('topscore_pal', 'Topscore PAL'), ('diatomeeenaarde', 'Diatomeeenaarde'), ('andere', 'Andere')], max_length=50, null=True),
        ),
    ]
