# Generated by Django 5.0.6 on 2024-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_alter_anb_administrator_alter_anb_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(blank=True, choices=[('permas_d', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('vespa_ficam_d', 'Vespa Ficam D'), ('topscore_pal', 'Topscore PAL'), ('diatomeeenaarde', 'Diatomeeënaarde'), ('ether_aceton_ethyl_acetate', 'Ether/Aceton/Ethyl Acetate'), ('vespa', 'VESPA'), ('andere', 'Andere')], help_text='Product used for the eradication', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nest_type',
            field=models.CharField(blank=True, choices=[('actief_embryonaal_nest', 'Actief embryonaal nest'), ('actief_primair_nest', 'Actief primair nest'), ('actief_secundair_nest', 'Actief secundair nest'), ('inactief_leeg_nest', 'Inactief/leeg nest'), ('potentieel_nest', 'Potentieel nest')], help_text='Type of the nest', max_length=50, null=True),
        ),
    ]
