# Generated by Django 5.0.6 on 2024-09-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0022_alter_municipality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_date',
            field=models.DateField(blank=True, help_text='Date when the nest was eradicated', null=True),
        ),
    ]
