# Generated by Django 5.0.6 on 2024-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0023_alter_observation_eradication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_duration',
            field=models.IntegerField(blank=True, help_text='Duration of the eradication in minutes', null=True),
        ),
    ]
