# Generated by Django 5.0.6 on 2024-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0025_convert_eradication_duration_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='nest_type',
            field=models.CharField(blank=True, choices=[('actief_embryonaal_nest', 'Actief embryonaal nest'), ('actief_primair_nest', 'Actief primair nest'), ('actief_secundair_nest', 'Actief secundair nest'), ('inactief_leeg_nest', 'Inactief/leeg nest')], help_text='Type of the nest', max_length=50, null=True),
        ),
    ]
