# Generated by Django 5.0.6 on 2024-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0026_alter_observation_nest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_product',
            field=models.CharField(blank=True, choices=[('permas_d', 'Permas-D'), ('vloeibare_stikstof', 'Vloeibare stikstof'), ('ficam_d', 'Ficam D'), ('topscore_pal', 'Topscore PAL'), ('diatomeeenaarde', 'Diatomeeënaarde'), ('ether_aceton_ethyl_acetaat', 'Ether, aceton of ethylacetaat'), ('vespa', 'Vespa'), ('andere', 'Andere')], help_text='Product used for the eradication', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='eradication_result',
            field=models.CharField(blank=True, choices=[('successful', 'Succesvol behandeld'), ('unsuccessful', 'Niet succesvol behandeld'), ('untreated', 'Niet behandeld want andere soort'), ('untreatable', 'Onbehandelbaar (bv. te hoog, inactief)'), ('unknown', 'Onbekend')], help_text='Result of the eradication', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.IntegerField(blank=True, help_text='Species of the observed nest', null=True),
        ),
    ]
