# Generated by Django 5.0.6 on 2024-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0027_alter_observation_eradication_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eradication_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the eradication in minutes', null=True),
        ),
    ]
