# Generated by Django 5.1.2 on 2024-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0030_alter_observation_observer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='Original identifier when importing data', null=True),
        ),
    ]
