# Generated by Django 5.1.2 on 2024-11-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0031_observation_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='wn_notes',
            new_name='notes',
        ),
    ]
