# Generated by Django 5.1.4 on 2025-01-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0033_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='species',
        ),
    ]
