# Generated by Django 5.1.4 on 2025-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0034_remove_observation_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, help_text='Datetime when the observation was made', null=True),
        ),
    ]
