# Generated by Django 5.1.4 on 2025-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0035_alter_observation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='queen_present',
            field=models.BooleanField(blank=True, help_text='Shows if the queen was present during the eradication', null=True),
        ),
    ]
