# Generated by Django 5.1.4 on 2025-03-23 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0037_observation_moth_present_alter_observation_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['visible', 'observation_datetime'], name='observation_visible_fd13d4_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['location'], name='location_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['municipality', 'visible'], name='observation_municip_02da50_idx'),
        ),
    ]
