# Generated by Django 5.1.4 on 2025-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0038_observation_observation_visible_fd13d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='duplicate_nest',
            field=models.BooleanField(blank=True, help_text='Shows if the nest is a duplicate', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='other_species_nest',
            field=models.BooleanField(blank=True, help_text='Shows if the nest belongs to another species', null=True),
        ),
    ]
