# Generated by Django 5.2.1 on 2025-05-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0039_observation_duplicate_nest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='filters',
        ),
        migrations.AlterField(
            model_name='export',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='file_path',
            field=models.CharField(null=True,blank=True, help_text='Path to the exported file in S3', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='export',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who initiated the export', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='created_datetime',
            field=models.DateTimeField(help_text='Datetime when the observation was created'),
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path to the uploaded file in S3', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the import', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage of the import')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when the import was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Datetime when the import was completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the import failed', null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for the import', max_length=255, null=True)),
                ('created_ids', models.JSONField(default=list, help_text='IDs of created observations')),
                ('updated_ids', models.JSONField(default=list, help_text='IDs of updated observations')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the import', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
