# Generated by Django 5.2.1 on 2025-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0040_remove_export_filters_alter_export_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='File Path'),
        ),
    ]
