# Generated by Django 5.2.1 on 2025-05-26 05:55

from django.db import migrations

def populate_filepath_default(apps, schema_editor):
    """
    Sets a default empty string for any Export records
    where file_path is currently NULL.
    """
    Export = apps.get_model('observations', 'Export')
    Export.objects.filter(file_path__isnull=True).update(file_path='')

class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_alter_export_file_path_alter_import_file_path'),
    ]

    operations = [
        migrations.RunPython(populate_filepath_default),
    ]
