# Generated by Django 5.2.1 on 2025-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_alter_export_file_path_alter_import_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
