# Generated by Django 5.2.1 on 2025-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0042_alter_export_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
