# Generated by Django 5.2.1 on 2025-05-29 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0043_alter_export_file_path_alter_import_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['province'], name='observation_provinc_f6ccee_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['anb'], name='observation_anb_433cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['nest_type'], name='observation_nest_ty_95e69f_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['eradication_result'], name='observation_eradica_d6ef8b_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['reserved_by'], name='observation_reserve_e053de_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observation_datetime', 'visible'], name='observation_observa_26bff8_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['eradication_date'], name='observation_eradica_13ba42_idx'),
        ),
    ]
