# Generated by Django 5.2.1 on 2025-06-07 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0044_alter_export_file_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['-observation_datetime'], name='observation_observa_b2ea93_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['wn_id'], name='observation_wn_id_820d66_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['eradicator_name'], name='observation_eradica_b8f04b_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observer_name'], name='observation_observe_08e526_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['modified_datetime'], name='observation_modifie_d224c9_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['reserved_datetime'], name='observation_reserve_ca02db_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['created_by', 'observation_datetime'], name='observation_created_60685c_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['municipality', 'observation_datetime'], name='observation_municip_da351a_idx'),
        ),
    ]
